### ISSUE TITLE
MegaSat Sat2IP Server RTSP 400

### ISSUE THREAD

**Issue by jmachowinski** [rofafor/vdr-plugin-satip#10]
Hey, 
after running for a while (minutes to days), my syslog gets spammed with
May 11 07:04:25 Server vdr: [1853] SATIP-ERROR: Detected invalid status code 400: rtsp://192.168.0.150/ [device 0]
May 11 07:04:25 Server vdr: [1853] SATIP-ERROR: Connect failed [device 0]
After this I can not receive any shows any more. A restart of VDR recoveres the 
error. The error is highly undeterministic, and I don't know what triggers it. I will 
try to get a network dump of the communication between the SAT2IP server and 
vdr on the weekend. 
Do you got any idea what could cause this error ?
Greetings

**Comment by rofafor** [comment]
My guess is an unstable satip stack on your device. You could capture the RTSP traffic when the malfunction occurs, so I might find a quirk or even fix to prevent it.

**Comment by jmachowinski** [comment]
Ok, I found some time to look into this. 
The network dump is quite big (40 MB), but I could upload it somewhere.
The code 400 comes from a timeout. A session is opened, then not used 
for a long time and then reuse again. At this point in time the session is 
already expired, which leads to the code 400 and the message 'Session unknown'.
Funnily enough the patches you added between the bug report and now seem to 
fix the problem. 
Anyway, the code should be able to recover from an invalid session. So, I also added this patch : 
https://github.com/jmachowinski/vdr-plugin-satip/commit/6e548fed1427e891797e4ce9ae62f1f88abe2328

In my syslog there are also some code 500 RTSP errors around (after the 400 vanished I discovered them).
They seem to be triggered by a missing ro
PLAY rtsp://192.168.0.150/stream=10142?freq=10847&src=1&sr=23000&pol=v&fec=56&mtype=qpsk&msys=dvbs2 RTSP/1.0\\r\\n
I'm not to sure how to interpret Page 43 of the SatIp Spec 1.2.2 but it looks like
dvb-s means dvb-s and dvb-s2.

I'm curious, why are there multiple sessions around in the first place ?

**Comment by rofafor** [comment]
The keep-alive messages should keep the sessions valid and therefore shouldn't occur any timeouts. You could upload the log somewhere and provide me the details via email.

Most likely your channels.conf contains rolloff auto values and there's no auto setting in SAT>IP. Please update your channels.conf accordingly and see whether the problem still exists.

**Comment by rofafor** [comment]
Did the channels.conf tweaks cure the issue? Can I close the issue?

**Comment by jmachowinski** [comment]
Hey, 
sorry for not responding. The issue seems to be fixed.
