### ISSUE TITLE
Recover from server crash

### ISSUE THREAD

**Issue by Zabrimus** [rofafor/vdr-plugin-satip#11]
Test case:
1. Start minisatip and VDR using the latest git version of vdr-plugin-satip
2. simulate server crash by killing minisatip
3. restart minisatip
4. restart  with 2. as often as necessary

Expected result:
VDR is operated  and shows the currently tuned channel.

Observed behavior:
VDR shows only a still image  and channel switch isn't working anymore. Only a restart of the VDR could help.

Logs from vdr-plugin-satip:

--- everything normal till the server dead and then

url_easy_perform() [rtsp.c,255] failed: Couldn't connect to server (7)
SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Couldn't connect to server (7)
SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Couldn't connect to server (7)
SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)
SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)

--- after restart of minisatip

SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)
SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)
SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)
SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.178.20/ [device 0]
curl_easy_perform() [rtsp.c,255] failed: Timeout was reached (28)
SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.178.20/ [device 0]

Logs on the server side (minisatip) after the restart:

read RTSP (from handle 10 sock_id 5, len: 0, sid -1):
DESCRIBE rtsp://192.168.178.20/stream=2 RTSP/1.0
CSeq: 80
Session: 0846930886
Accept: application/sdp
User-Agent: vdr-satip/2.2.3-GIT-49e2dd1 (device 0)
If-Modified-Since: Thu, 01 Jan 1970 00:00:00 GMT

reply -> 10 (192.168.178.20:47716) CL:0 :
RTSP/1.0 404 Not Found
Date: Mon, Aug 10 18:43:53 2015 GMT
Cseq: 80
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN

It seems that the plugin only sends DESCRIBE for an already unknown stream and does not handle or retune or something else after getting the 404 response.

**Comment by rofafor** [comment]
I'm unable to reproduce your problem (svdrpsend plug satip trac 0x18):

1. stopping minisatip:

Aug 16 00:13:49 minipossu vdr[3497]: [3543] curl_easy_perform() [rtsp.c,284] failed: Couldn't connect to server (7)
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.0.5/ [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://192.168.0.5/stream=1?addpids=281&delpids=258) Response 0 in 1 ms [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP-ERROR: Pid update failed - retuning [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP4: virtual void cSatipTuner::Action(): tsSet [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] curl_easy_perform() [rtsp.c,284] failed: Couldn't connect to server (7)
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.0.5/ [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://192.168.0.5/stream=1?freq=562&bw=8&gi=18&fec=23&mtype=64qam&msys=dvbt&tmode=8k) Response 0 in 0 ms [device 0]
Aug 16 00:13:49 minipossu vdr[3497]: [3543] SATIP-ERROR: Connect failed [device 0]

2) restarting minisatip

Aug 16 00:13:56 minipossu vdr[3497]: [3543] curl_easy_perform() [rtsp.c,165] failed: Couldn't connect to server (7)
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.0.5/ [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Options(const char*) (rtsp://192.168.0.5/) Response 0 in 0 ms [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP-ERROR: Connect failed [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Options(const char*) (rtsp://192.168.0.5/) Response 200 in 202 ms [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Setup(const char*, int, int) (rtsp://192.168.0.5/?freq=562&bw=8&gi=18&fec=23&mtype=64qam&msys=dvbt&tmode=8k, 43399, 43400) Response 200 in 0 s [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://192.168.0.5/stream=1?pids=0,16,17,18,20,281,513,660,664,2027,5000) Response 200 in 43 ms [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP4: virtual void cSatipTuner::Action(): tsTuned [device 0]
Aug 16 00:13:56 minipossu vdr[3497]: [3543] SATIP5: bool cSatipRtsp::Describe(const char*) (rtsp://192.168.0.5/stream=1) Response 200 in 1 ms [device 0]

**Comment by Zabrimus** [comment]
Strange. I have done my very best to reproduce this error with the latest version of your plugin - without success. 
Either the problem is fixed, or my first test cases (which were reproducible) had a special constellation, which doesn't exists anymore.
I have installed the plugin on one of my production system (PI 2) and it works also. But now i have some problems with dvbapi. 

(some times later)

After enabling dvbapi in minisatip, i have the same error as mentioned in the first post. I need to do some more tests to get a rock solid satip infrastructure.

**Comment by rofafor** [comment]
Well, I updated the repo yesterday and added code to prevent infinite tuning loops, so now you should get erroneous DESCRIBE answers no more than 20 seconds before re-tuning.

Please, let me know if I can close the issue.

**Comment by Zabrimus** [comment]
I reserved only one tuner for the server and disabling epg scan and the parameter "-d 1" do the trick. No more problems, very fast channel switch, several server restarts without a vdr problem... i'm happy. 

Many thanks
