### ISSUE TITLE
SATIP-ERROR: invalid status code 454

### ISSUE THREAD

**Issue by jakubklos77** [rofafor/vdr-plugin-satip#12]
Hello
I am trying to use this VDR plugin but I am having issues.
Please, see the log below:

Sep 16 12:01:10 Media vdr: [30749] SATIP: Adding server '192.168.0.18|DVBS2-4|Schwaiger Sat>IP Server' CI: no Quirks: none
Sep 16 12:01:18 Media vdr: [30736] switching to channel 1 (CT1)
Sep 16 12:01:18 Media vdr: [30736] OSD size changed to 720x480 @ 1
Sep 16 12:01:18 Media vdr: [30736] ERROR: no OSD provider available - using dummy OSD!
Sep 16 12:01:19 Media vdr: [30750] curl_easy_perform() [rtsp.c,255] failed: RTSP session error (86)
Sep 16 12:01:19 Media vdr: [30750] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.0.18/ [device 0]
Sep 16 12:01:20 Media vdr: [30750] curl_easy_perform() [rtsp.c,255] failed: RTSP session error (86)
Sep 16 12:01:20 Media vdr: [30750] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.0.18/ [device 0]
Sep 16 12:01:21 Media vdr: [30750] curl_easy_perform() [rtsp.c,255] failed: RTSP session error (86)
Sep 16 12:01:21 Media vdr: [30750] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.0.18/ [device 0]

Can we please troubleshoot this issue? I have tried with 2.2.2 and 2.3.1 and it is the same
Will you please help me to get this working?

Running on Ubuntu 14.04 and VDR 2.2.0

Thank you,
Jakub

**Comment by rofafor** [comment]
What's the version of your libcurl?

**Comment by jakubklos77** [comment]
I have checked the tcpdump. This is the response to the SETUP command

RTSP/1.0 200 OK
Session:5da2e9e27f99db3a;timeout=30
com.ses.streamID:1600
Transport:RTP/AVP;unicast;destination=192.168.0.5;client_port=47025-47026
CSeq:2


And this is what the plugin sends back in the DESCRIBE command

DESCRIBE rtsp://192.168.0.18/stream=1600 RTSP/1.0
CSeq: 3
Session: da2e9e27f99db3a
Accept: application/sdp
User-Agent: vdr-satip/2.2.3 (device 0)
If-Modified-Since: Thu, 01 Jan 1970 00:00:00 GMT

You can see the first character is missing in the session id. So it is omitted for some reason.

Btw:
libcurl 7.35.0


Thank you

**Comment by rofafor** [comment]
Your libcurl version contains a session bug. Please, upgrade to libcurl 7.36.0 or newer as stated in README.

**Comment by jakubklos77** [comment]
Thank you very much
This seems to help
Now I am getting this error
Sep 17 10:16:11 Media vdr: [31783] SATIP-ERROR: Tuning timeout - retuning [device 0]

Btw. the DVB-S2 card works fine with VDR (using the same channels) and the SatIP device also works properly (tested some Windows sw and Tvheadend (which does not work well))

I have not done extra setup of the plugin as I didn't undestand if it is required.
Thank you again. Your help much appreciated

**Comment by jakubklos77** [comment]
I was able to get it all working. Appears that error message is not fatal and it works fine after.

What I am strugging now with is the DVBAPI plugin and Oscam.
When using a DVB device it works properly but when using a SatIP device it does not

Can you think of any solution? Thank you again.

syslog:
Sep 17 16:27:46 Media vdr: [27980] streamdev-writer thread started (pid=27890, tid=27980, prio=high)
Sep 17 16:27:46 Media vdr: [27981] streamdev-livestreaming thread started (pid=27890, tid=27981, prio=high)
Sep 17 16:27:46 Media vdr: [27907] DVBAPI: 2.0 set CAM decrypt (SID 31002 (0x791A), caLm 4, HasCaDescriptors 0)
Sep 17 16:27:46 Media vdr: [27982] device 3 receiver thread started (pid=27890, tid=27982, prio=high)
Sep 17 16:28:01 Media CRON[28025]: (root) CMD (/emu/cron.sh >/dev/null 2>&1)
Sep 17 16:28:39 Media vdr: [27907] client (HTTP) 192.168.0.2:49185 has closed connection
Sep 17 16:28:39 Media vdr: [27907] streamdev-server: closing HTTP connection to 192.168.0.2:49185
Sep 17 16:28:39 Media vdr: [27907] DVBAPI: 2.0 set CAM decrypt (SID 31002 (0x791A), caLm 5, HasCaDescriptors 0)
Sep 17 16:28:39 Media vdr: [27907] CAM 1: unassigned
Sep 17 16:28:39 Media vdr: [27982] device 3 receiver thread ended (pid=27890, tid=27982)
Sep 17 16:28:39 Media vdr: [27981] streamdev-livestreaming thread ended (pid=27890, tid=27981)
Sep 17 16:28:39 Media vdr: [27980] streamdev-writer thread ended (pid=27890, tid=27980)
Sep 17 16:28:39 Media vdr: [27907] buffer stats: 0 (0%) used
Sep 17 16:28:42 Media vdr: [27894] SATIP: Detected 1 RTP packet errors [device 0]
Sep 17 16:28:44 Media vdr: [27907] Streamdev: Accepted new client (HTTP) 192.168.0.2:49209
Sep 17 16:28:44 Media vdr: [27907] CAM 1: assigned to device 1
Sep 17 16:28:44 Media vdr: [28171] streamdev-writer thread started (pid=27890, tid=28171, prio=high)
Sep 17 16:28:44 Media vdr: [28172] streamdev-livestreaming thread started (pid=27890, tid=28172, prio=high)
Sep 17 16:28:44 Media vdr: [27907] DVBAPI: 2.0 set CAM decrypt (SID 31002 (0x791A), caLm 4, HasCaDescriptors 0)
Sep 17 16:28:44 Media vdr: [28173] device 3 receiver thread started (pid=27890, tid=28173, prio=high)
S

OSCam log
16:27:20 6B4D5D1C c   (dvbapi) Client connected: 'vdr-plugin-dvbapi 2.2.1-GIT-ce8a124 / VDR 2.2.0' (protocol version = 2)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 1815 ECM_PID: 1389 PROVID: 000000
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0D02 ECM_PID: 14B5 PROVID: 000000
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0B02 ECM_PID: 15E1 PROVID: 000000
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0D97 ECM_PID: 170D PROVID: 000000
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 0653 ECM_PID: 1839 PROVID: 000000
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 skipped stream CAID: 1815 ECM_PID: 1389 PROVID: 000000 (Same as ECMPID 0)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 skipped stream CAID: 0D02 ECM_PID: 14B5 PROVID: 000000 (Same as ECMPID 1)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 skipped stream CAID: 0B02 ECM_PID: 15E1 PROVID: 000000 (Same as ECMPID 2)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 skipped stream CAID: 0D97 ECM_PID: 170D PROVID: 000000 (Same as ECMPID 3)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 skipped stream CAID: 0653 ECM_PID: 1839 PROVID: 000000 (Same as ECMPID 4)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 found 5 ECMpids and 2 STREAMpids in PMT
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 serving srvid 791A (1815@000000:791A unknown) on adapter 0002 camask 0004 index 0000 pmtpid 0000
16:35:52 6B4D5D1C c   (dvbapi) ERROR: Can't open device /dev/dvb/adapter2/demux0 (errno=2 No such file or directory)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 3
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 trying to descramble PID 3 CAID 0D97 PROVID 000000 ECMPID 170D ANY CHID PMTPID 0000 VPID 0097
16:35:52 6B4D5D1C c   (dvbapi) ERROR: Can't open device /dev/dvb/adapter2/demux0 (errno=2 No such file or directory)
16:35:52 6B4D5D1C c   (dvbapi) Demuxer 0 restarting decodingrequests after 0 ms with 1 enabled and 4 disabled ecmpids!

**Comment by rofafor** [comment]
For the re-tuning issue, you could try to add a force lock quirk for your device into server.c:

```
     // These devices contain a frontend locking bug:
-     if (strstr(*descriptionM, "fritzdvbc")             // Fritz!WLAN Repeater DVB-C
+     if (strstr(*descriptionM, "fritzdvbc") ||          // Fritz!WLAN Repeater DVB-C
+         strstr(*descriptionM, "Schwaiger Sat>IP Server")
```

**Comment by rofafor** [comment]
Please, don't use the streamdev plugin for testing as it has known issues with decryption.

**Comment by jakubklos77** [comment]
Thank you, I have done the patch to the frontend locking.

Regarding the decryption, it still does not work properly.
As soon as there is any ongoing any encryption going on any secondary (on another device) fails and never works.

- I can open a non scrambled channel (on any device) and keep it running (DVB or SatIP)
- then I can open a scrambled and all is working fine (SatIP)

- if there is an open scrambled channel already showing and I display another scrambled channel over SatIP it does not work.

Not testing with streamdev but vnsiserver.
Any guide lines?

I receive one of these in such situation
16:35:52 6B4D5D1C c (dvbapi) ERROR: Can't open device /dev/dvb/adapter2/demux0 (errno=2 No such file or directory)

Thank you for your help

**Comment by jakubklos77** [comment]
I know this has probably nothing to do with your great vdr plugin but if you have any advices. Thank you again

**Comment by rofafor** [comment]
Your decryption problems aren't directly related to satip plugin, so there's no point having such conversation here.

However, did the re-tuning patch fix your system? If yes, I'll add it into repo.

**Comment by jakubklos77** [comment]
I think so, I haven't seen that error ever since

**Comment by rofafor** [comment]
Great! Pushed the fix to master and let's close this issue.
