### ISSUE TITLE
MIS Support for Multistream Transponders dvbs

### ISSUE THREAD

**Issue by 9000h** [rofafor/vdr-plugin-satip#13]
if you like you may add the change fro Yuri
https://toda.ro/forum/viewtopic.php?f=5&t=3&start=10

**Comment by rofafor** [comment]
SAT>IP specification allows the 'plp' parameter only for DVB-T2 and DVB-C2 channels and the valid values are between 0 and 255. Adding it to the DVB-S* channels with out-of-range values might break up the support for servers other than the minisatip, so I won't add such a hack into my repo.
