### ISSUE TITLE
Server gets removed if behind a NAT

### ISSUE THREAD

**Issue by chriszero** [rofafor/vdr-plugin-satip#17]
Hi,
After the last enhancement it's possible to use the plugin behind a NAT, this works only for a a about 3 minutes. Then the manually added (via command-line) server is removed.

    2016-01-09T12:10:24.751437+01:00 0a666b41677b vdr: [124] SATIP: Adding server '192.168.1.142|DVBC-4|Octo1' CI: no Quirks: none
    ...
    2016-01-09T12:13:25.782311+01:00 0a666b41677b vdr: [143] SATIP: Removing server Octo1 (192.168.1.142 DVBC-4)

I suspect the cSatipServer::Update() is not called because the cSatipDiscover cannot detect any Satip-servers behind the NAT.
I would propose to disable the automatic cleanup for servers which are added via command-line parameter.

**Comment by rofafor** [comment]
More info about your setup, please. If you're defining the servers via a command-line parameter, the discovery+cleanup thread should never be started and therefore the cSatipServers::Cleanup() method should never run. Also the cleanup timeout is 124s and that hardly matches to your 180s.

**Comment by chriszero** [comment]
Nevermind, I couldn't reproduce this after I set up a new vdr installation...
