### ISSUE TITLE
TVHeadend support

### ISSUE THREAD

**Issue by goerdi** [rofafor/vdr-plugin-satip#19]
What about support for 
a) support for tvheadend sat>ip server
b) different rtsp port

a) sat>ip works perfekt with dvbviewer and elgato sat>ip
b) would be nice bec. e.g. tvh in usermode server runs on port 9983

Ciao gerd

**Comment by rofafor** [comment]
I don't currently have any suitable development setup for a such compo, so don't expect any quick solution. Does my plugin work, if you're running the tvheadend sat>ip server on a standard RTSP port 554 (starting as root and dropping all the priviledges but net)?

**Comment by goerdi** [comment]
Hi !

No with RTSP Port 554 your plugin see the server but it won't work

Ciao Gerd

**Comment by rofafor** [comment]
Could you provide debug output of the satip plugin in that case? Just enable the debugging (svdrpsend plug satip trac 0x112), do a few channel zapping, and finally grep every line containing a string 'SATIP' from your syslog.

**Comment by goerdi** [comment]
sry 4 delay.. i tried again from scratch and .. it seems to work.. I have problems with a few channels but therefore i have to investigate if it a problem of satip plugin or the tvheadend serd

**Comment by goerdi** [comment]
sry 4 delay.. i tried again from scratch and .. it seems to work.. I have problems with a few channels but therefore i have to investigate if it a problem of satip plugin or the tvheadend 
Ciao Gerd

**Comment by rofafor** [comment]
Great to hear. I'll add support for TVHeadend's X-SATIP-RTSP-Port header to get it working on a non-standard ports too.

**Comment by rofafor** [comment]
Can you check whether the following code works for you? It should contain support for running TVHeadend server on a non-standard RTSP server:
https://github.com/rofafor/vdr-plugin-satip/tree/tvheadend

**Comment by rofafor** [comment]
Please, reopen the issue, if it doesn't work.
