### ISSUE TITLE
Option for DISABLE some server

### ISSUE THREAD

**Issue by lars18th** [rofafor/vdr-plugin-satip#20]
Hi,

This plugin works well. Thank you for it!

However, in my setup I have different SAT>IP servers, and sometimes I don't like to use one of them. Please, can you add the option for DISABLE some specific server?

At time, I'm using the command line option -P 'satip -s 192.168.0.1|DVBS2-2' but this only "adds" the server, not force to use only the listed.

I hope you can implement this.
Regards!

**Comment by rofafor** [comment]
I prefer white-listing and therefore if you define your servers via command-line, the server autodiscovery should be disabled. Can you elaborate your use case a bit more detailed? You want to "detach" one of the servers via SVDRP instead of all?

**Comment by lars18th** [comment]
Hi,

Thank you for the response!

I like to "black-list" some server, not all. I prefer to do it "on-the-fly", and not using the command line. But any solution is welcome...

Here the different options:

1) Add one command line option for DISABLE "auto-discovering" (then any listed server in the command line will be the only one to use).

2) One command line option for black-list a server (I suggest to use IP wildcards, like 192.168.1.64/31)

3) One user interface option for check-uncheck a server and not use it.

I hope you can implement some of them.
Regards!

**Comment by rofafor** [comment]
1) Already implemented
2) The command-line option will be either a white-listing one as now or a blacklisting one if you really prefer it. I won't implement any mix up.
3) This might be a viable solution: GUI + SVDRP

**Comment by lars18th** [comment]
Hi,

> 1) Already implemented

Sorry! Where is?

> 2) The command-line option will be either a white-listing one as now 
> or a blacklisting one if you really prefer it. I won't implement any mix up.

If you implement a simple "disable all (except white listed)" in the command line it's perfect!

> 3) This might be a viable solution: GUI + SVDRP

This will be the best! :)

Regards!

**Comment by rofafor** [comment]
1) If you define "-s" parameter on the command-line, the auto-discovery is disabled and only the defined servers are used.

**Comment by lars18th** [comment]
Hi @rofafor ,

> 1) If you define "-s" parameter on the command-line, the auto-discovery 
> is disabled and only the defined servers are used.

I'll check, because in my first trials when I use the "-s" parameter de auto-discovery continues working (other servers appears in the search). This is the reason for opening this issue. Perhaps the version I'm using is quite old.

Also, I hope you soon can implement the option "3". ;)

Thank you!

**Comment by rofafor** [comment]
Sorry for the delay, but I've now committed a solution to activate/deactivate SAT>IP servers via the setup menu. No SVDRP support at the moment and mode changing requires re-zapping before taken in account.

**Comment by srehm** [comment]
Hello rofafor,

are you sure the implementation of cSatipServer::Assign in cede474 is correct? I am just wondering since it stops iterating over all the servers once it finds a disabled one. Is the list sorted so that the disabled ones are at the end? If not, wouldn`t it be better if the mehtod was implemented like the following?

cSatipServer *cSatipServers::Assign(int deviceIdP, int sourceP, int transponderP, int systemP) {
    for (cSatipServer *s = First(); s; s = Next(s)) {
       if (s->IsActive() && s->Matches(deviceIdP, sourceP, systemP, transponderP))
          return s;
       }
    for (cSatipServer *s = First(); s; s = Next(s)) {
       if (s->IsActive() && s->Assign(deviceIdP, sourceP, systemP, transponderP))
          return s;
       }
    return NULL;
}

**Comment by lars18th** [comment]
Hi @rofafor ,

Thank you for the commit!
http://github.com/rofafor/vdr-plugin-satip/commit/cede4743cbe1fad93c60744ce9d7b989bd4c8577

Regards!

**Comment by rofafor** [comment]
@srehm, ah, thanks for your review! You're correct and my initial implementation was such, but decided to optimize a bit prettier and broke the implementation at the same time.
