### ISSUE TITLE
HUMAX Digital UHD 4tune+ - SATIP-ERROR: Detected invalid status code 454

### ISSUE THREAD

**Issue by edy1234** [rofafor/vdr-plugin-satip#30]
Hi, 

every now and again, usually every 10 to 30 minutes, I get a short loss of picture or scramble when watching TV with the satip plugin. When that happens it always seems to coincide with a "SATIP-ERROR: Detected invalid status code 454", immediately followed by "SATIP-ERROR: Connect failed [device 0]" and then "SATIP: Detected 1 RTP packet errors [device 0]"

This happens with HD, as well as SD free-to-air channels.

My system journal says this with satip trac 0x12 enabled. I hope the excerpt is enough.

```
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 200 OK
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:48 GMT
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Session: 1D6AB6B4
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 1007
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTP-Info: url=rtsp://10.0.0.2/stream=10
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:48 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://10.0.0.2/stream=10?addpids=6300) Response 200 in 35 ms [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Found bundle for host 10.0.0.2: 0x5e98b0 [can pipeline]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Re-using existing connection! (#0) with host 10.0.0.2
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:52 bananapipro vdr[3178]: [237B blob data]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 454 Session Not Found
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:52 GMT
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 1008
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Options(const char*) (rtsp://10.0.0.2/) Response 454 in 8 ms [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP-ERROR: Keep-alive failed - retuning [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Found bundle for host 10.0.0.2: 0x5e98b0 [can pipeline]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Re-using existing connection! (#0) with host 10.0.0.2
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:52 bananapipro vdr[3178]: [312B blob data]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 454 Session Not Found
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:52 GMT
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 1009
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://10.0.0.2/stream=10?src=1&freq=11362&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23) Response 454 in 49 ms [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP-ERROR: Connect failed [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO   Trying 10.0.0.2...
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:52 bananapipro vdr[3178]: [215B blob data]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 200 OK
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:52 GMT
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 1
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Options(const char*) (rtsp://10.0.0.2/) Response 200 in 50 ms [device 0]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Found bundle for host 10.0.0.2: 0x5e9110 [can pipeline]
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Re-using existing connection! (#0) with host 10.0.0.2
Sep 22 23:41:52 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:52 bananapipro vdr[3178]: [334B blob data]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 200 OK
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:52 GMT
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 2
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Session: 10A26920;timeout=60
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< com.ses.streamID: 12
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Transport: RTP/AVP;unicast;destination=10.0.0.1;source=10.0.0.2;client_port=48400-48401;server_port=40076-51125
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Setup(const char*, int, int, bool) (rtsp://10.0.0.2/?src=1&freq=11362&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23, 48400, 48401) Response 200 in 423 ms [device 0]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Found bundle for host 10.0.0.2: 0x5e9110 [can pipeline]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Re-using existing connection! (#0) with host 10.0.0.2
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:53 bananapipro vdr[3178]: [299B blob data]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 200 OK
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:52 GMT
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Session: 10A26920
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 3
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTP-Info: url=rtsp://10.0.0.2/stream=12
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 0
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Play(const char*) (rtsp://10.0.0.2/stream=12?pids=0,16,17,18,20,6300,6310,6320,6321,6322,6323,6330,6331) Response 200 in 100 ms [device 0]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Found bundle for host 10.0.0.2: 0x5e9110 [can pipeline]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Re-using existing connection! (#0) with host 10.0.0.2
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connected to 10.0.0.2 (10.0.0.2) port 554 (#0)
Sep 22 23:41:53 bananapipro vdr[3178]: [269B blob data]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< RTSP/1.0 200 OK
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Date: Thu, 22 Sep 2016 21:41:53 GMT
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Type: application/sdp
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Base: rtsp://10.0.0.2/
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Content-Length: 266
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< CSeq: 4
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<< Session: 10A26920
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP HEAD <<<
Sep 22 23:41:53 bananapipro vdr[3178]: [385B blob data]
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP2: static int cSatipRtsp::DebugCallback(CURL*, curl_infotype, char*, size_t, void*) [device 0] RTSP INFO Connection #0 to host 10.0.0.2 left intact
Sep 22 23:41:53 bananapipro vdr[3178]: [3184] SATIP5: bool cSatipRtsp::Describe(const char*) (rtsp://10.0.0.2/stream=12) Response 200 in 82 ms [device 0]
Sep 22 23:41:53 bananapipro vdr[3178]: [3183] SATIP: Detected 1 RTP packet errors [device 0]
```

my setup:
satip server: HUMAX Digital UHD 4tune+. The server has no configuration possibilities other than name and IP, so I can't fiddle around with any settings on the server itself.
vdr 2.2.0 runs on a Banana Pi Pro (IP 10.0.0.1 in the log) that's directly connected through the ethernet port with the Humax satip server (IP 10.0.0.2 in the log)
satip plugin version is the current git version from the 2.2.x branch (earlier tonight I also compiled a version that enables the existing server.c SessionID quirk for my server, but that didn't solve the issue).
libcurl version: 7.47.0-1ubuntu2.1

Any help would be greatly appreciated. If a tcpdump is needed, I'd need some directions on what command to use to capture the desired output.

**Comment by rofafor** [comment]
It looks like that your server sometimes invalidates the active session for no reason. Now, there are two things you could try:
1) Add stream id into keep-alive messages
2) Disable keep-alive messages
```
bool cSatipTuner::KeepAlive(bool forceP)
{
   ...
  if (forceP && !isempty(*streamAddrM)) {
     cString uri = GetBaseUrl(*streamAddrM, streamPortM);
     // option #1: add stream id into keep-alive messages
     if (streamIdM >= 0)
        uri = cString::sprintf("%sstream=%d", *uri, streamIdM);
     // end of option #1
     // option #2: disable keep-alive messages
     return true;
     // end of option #2
     if (!rtspM.Options(*uri))
        return false;
     }
   ...
}
```
Does the server work properly with other clients?

**Comment by edy1234** [comment]
Thanks for the quick answer and suggestions. I tried both options (tuner.c was the correct place, right?), but neither version solved the problem.

As for other clients: Tvheadend, on the few versions I tried, freezes/crashes the server (the receiver part of the device keeps working, but I have to unplug the power cable to get the server part started again). Same story with an older version of your plugin that I had previously installed from a repository. Think it was 2.2.3. With the current version from git that never happens anymore.

DVBViewer Lite (Windows) and the HD+ app for Android seemed to work when I tried them, but I haven't tested them extensively yet because neither platform was my intended target.

**Comment by rofafor** [comment]
Yes, please. It would be great, if you'd be able to tcpdump all RTSP & RTCP packets during one hour with a working Windows client and with a vdr-satip setup.

**Comment by edy1234** [comment]
sure, but I'm not familiar with traffic sniffing at all. Can you point me towards what command to use to get the desired output?

Would "tcpdump -i [interface name, eth0 in my case] udp port 554 -w filename.txt" be correct to use on the vdr setup? I know the server uses port 554. With Wireshark on windows I could use basically the same filter from what I understand, right?

Thanks again for you help!

**Comment by edy1234** [comment]
Ok, I ended up using "tcpdump -i eth0 -A -s 0 -w [filename].pcap port 554" and hope that captured the information you asked for. I used the same channel each time and just kept that channel running for about an hour. Captured DVBviewer Lite on Windows and twice with your plugin, once unmodified and also with the option 1 you suggested yesterday.

[satipdumps.zip](https://github.com/rofafor/vdr-plugin-satip/files/490921/satipdumps.zip)

**Comment by rofafor** [comment]
It seems that Humax just can't handle the VDR. VDR is constantly scanning all the PMT pids, but DVBViewer is kind of static installation setting pids only at startup.
Now, you could try increasing the ePidUpdateIntervalMs in tuner.h into one second or even greater to slow down the pid scanning or simply dropping all pid updates after connecting by initializing a 10 second timer (tuner.c#140) and disabling all pid updates according to it (tuner.c#410).

**Comment by edy1234** [comment]
I don't know how to do the 2nd one, sadly I don't know any programming, but setting the ePidUpdateIntervalMs to a higher value worked really well. No errors at all anymore. Set it to a really high number, 30 seconds, for now though after 1, 5 and 10 seconds all troubled the server at least occasionally. Will see what number I'll be able to settle with eventually.

So thank you again. Problem solved :D

**Comment by rofafor** [comment]
That's great to hear. Can you provide me the "Adding server" line from your VDR logs, so I'll add a special quirk for the Humax?

**Comment by edy1234** [comment]
Oh, sure. It is

SATIP: Adding server '192.168.0.210|DVBS2-4|HGS-1000S SAT>IP SERVER 192.168.0.210' Filters: none CI: no Quirks: none

**Comment by rofafor** [comment]
Can you, please, try the following patch:
https://gist.github.com/rofafor/d2868f11c59efc53e6c24e106ba1c8b9

**Comment by edy1234** [comment]
That patch produces error sequences like

Sep 26 23:49:45 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:49:45 bananapipro vdr[21057]: [21063] SATIP-ERROR: Keep-alive failed - retuning [device 0]
Sep 26 23:49:45 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:49:45 bananapipro vdr[21057]: [21063] SATIP-ERROR: Connect failed [device 0]
Sep 26 23:51:47 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:51:47 bananapipro vdr[21057]: [21063] SATIP-ERROR: Keep-alive failed - retuning [device 0]
Sep 26 23:51:47 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:51:47 bananapipro vdr[21057]: [21063] SATIP-ERROR: Connect failed [device 0]
Sep 26 23:53:48 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:53:48 bananapipro vdr[21057]: [21063] SATIP-ERROR: Keep-alive failed - retuning [device 0]
Sep 26 23:53:48 bananapipro vdr[21057]: [21063] SATIP-ERROR: Detected invalid status code 454: rtsp://10.0.0.2/ [device 0]
Sep 26 23:53:48 bananapipro vdr[21057]: [21063] SATIP-ERROR: Connect failed [device 0]
Sep 26 23:53:50 bananapipro vdr[21057]: [21062] SATIP: Detected 3 RTP packet errors [device 0]

tcpdump: [patched.txt](https://github.com/rofafor/vdr-plugin-satip/files/494201/patched.txt)

Also, I don't know if it's related to the changes in the patch, or if it was a mere coincidence, but the humax also locked up in the way that I had to unplug it to get the server part started again. That hadn't happened at all since I updated from the 2.2.3 release version to one from git a week or two ago. The lockup/crash happened before I started logging, so I don't have any logs for it.

**Comment by rofafor** [comment]
The latest capture revealed another possible bug. Humax announces 60s timeout, but we're sending keep-alive messages with 60.05s interval and it might be, that this tiny difference might make Humax to invalidate the session. Could you change the line in tuner.c#L366:
```
- timeoutM = (timeoutP > eMinKeepAliveIntervalMs) ? timeoutP : eMinKeepAliveIntervalMs;
+ timeoutM = (timeoutP > eMinKeepAliveIntervalMs) ? timeoutP - 1 : eMinKeepAliveIntervalMs;
```

**Comment by edy1234** [comment]
That doesn't work too well either.

Sometimes it doesn't switch to the channels at all, and if it does there are the packet losses and picture errors that I originally opened the issue for. The server part of the Humax also crashed/locked up two more times while using this patched version, once with tcpdump running so maybe it caught something. I'm relatively sure it's connected to the changes.

I made three logs. The first one is just general usage. No crash, but the other errors will be in there

[patched2.txt](https://github.com/rofafor/vdr-plugin-satip/files/498759/patched2.txt)

2nd log is a short one for the switching channels issue because I didn't know how easily visible that is in the first log. 1st and last channel didn't work, the ones inbetween did. 

[switchingchannels.txt](https://github.com/rofafor/vdr-plugin-satip/files/498761/switchingchannels.txt)

Lastly, the log during which the humax server crashed.

[crash.txt](https://github.com/rofafor/vdr-plugin-satip/files/498767/crash.txt)

**Comment by rofafor** [comment]
Next time when you're debugging use only one active device. The network logs are rather heavy to read while multiple devices are accessing the server simultaneously. The server doesn't crash totally, but prevents any new resources to be created. The keep-live interval isn't the one I was expecting, so make sure that the only source code modification is commenting the earlier mentioned timeoutM setting line instead of trying to modify the value.

**Comment by edy1234** [comment]
oh right, I forgot to change it back to one device, sorry.

This is the tcpdump with only that line commented out, without the quirk patch added to the source.

[timeout.txt](https://github.com/rofafor/vdr-plugin-satip/files/507772/timeout.txt)

**Comment by rofafor** [comment]
Thanks. Great capture, but unfortunately I couldn't spot anything wrong or odd. Everything seems to be working quite nicely, but suddenly Humax misses its' session and vdr-satip has to re-tune that's causing some artifacts on the screen. Sorry, I can't figure out what to do next.

**Comment by edy1234** [comment]
Don't worry, you helped tremendously already with the advice to change the ePidUpdateIntervalMs.

**Comment by rofafor** [comment]
So, which value you ended up? I could add a proper quirk for it for the next release.

**Comment by edy1234** [comment]
I haven't spent too much time figuring the lowest possible value out yet because I've been more fiddling around with newer tvheadend builds instead of vdr as a backend the last few days. I know 20 seconds still caused that error, albeit in longer intervalls than normal. 25 and 30 seconds didn't cause that error in my tries (or maybe the errors are just so far apart that they don't happen in normal tv watching scenarios, not sure).

**Comment by rofafor** [comment]
Thanks for the info. I'll be closing the issue now as you've been shifting to another software. If any new information appears, please, re-open the issue.
