### ISSUE TITLE
PMT pid is added/deleted continuously

### ISSUE THREAD

**Issue by REELcoder** [rofafor/vdr-plugin-satip#31]
Hi,
After having issues with streaming to VLC from the streamdev-server, I detected that not all PMTs are received by cStreamdevLiveReceiver::Receive(). 

This happens both when receiving DVB-S from minisatip and DVB-C from OctopusNET. When locking at the RTSP requests comming from vdr-plugin-satip, there are continuous addpids/delpids with the PMT PID of the streamed channel.  This happens for both scrambled and unscrambled channels. 

Here an example from "Das Erste HD" with PMT PID 5100. The PID is added/removed several times per second:

```
No.     Time           Arrival Time       Source                Destination           Protocol Length Info
      4 0.132521       17:05:46.451647    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
     10 0.604172       17:05:46.923298    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0
     34 1.962518       17:05:48.281644    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
     43 2.445167       17:05:48.764293    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0
     61 3.722960       17:05:50.042086    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
     70 4.186928       17:05:50.506054    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0
     94 5.537540       17:05:51.856666    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
    103 6.011867       17:05:52.330993    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0
    124 7.395202       17:05:53.714328    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
    130 7.859299       17:05:54.178425    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0
    151 9.148314       17:05:55.467440    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5100&delpids=5130 RTSP/1.0
    157 9.622293       17:05:55.941419    10.76.1.1             10.76.1.1             RTSP     219    PLAY rtsp://10.76.1.1/stream=4?addpids=5110&delpids=5100 RTSP/1.0

```

What is the reason for this continuous addpids/delpids requests? BTW: its the vdr-2.2.0 branch.

**Comment by rofafor** [comment]
The core VDR is doing continuously PMT scanning. You'll need to take a look at the pat.c for disabling it.

**Comment by REELcoder** [comment]
OK. Thanks for the hint.

**Comment by REELcoder** [comment]
Strange. I can see no calls to cDevice::AddPid() / DelPid(). But satip sends addpids/delpids requests.

I propose to reopen this issue.

**Comment by rofafor** [comment]
But those are purely Receiver related stuff and therefore not directly related to satip plugin. Input plugins are driven purely by SetPid():

>   virtual bool SetPid(cPidHandle *Handle, int Type, bool On);
         ///< Does the actual PID setting on this device.
         ///< On indicates whether the PID shall be added or deleted.
         ///< Handle->handle can be used by the device to store information it
         ///< needs to receive this PID (for instance a file handle).
         ///< Handle->used indicates how many receivers are using this PID.
         ///< Type indicates some special types of PIDs, which the device may
         ///< need to set in a specific way.

**Comment by REELcoder** [comment]
Thanks again, I learn in small steps...

The addpid/delpid is due to calls to OpenFilter()/CloseFilter(). Now what happens, is that PMT PID previously activated by SetPid() is deactivated by CloseFilter(), obviously due to SwitchToNextPmtPid(). 

Is the deactivation of a PID by CloseFilter(), which was previously selected with SetPid(), done intentionally? When I read the cDevice documentation it is not obvious that this shall happen.

**Comment by rofafor** [comment]
Well, I tried to mimic the behavior of cDvbDevice::OpenFilter/CloseFilter(): if the filter is closed, there's no need for the pid data either. However, I haven't verified what happens if there are multiple active filters for the same pid. It might be, that PMT scanning disables streamdev filters as well when switching to next PMT and it just happens to work somehow with Linux DVB API.

**Comment by REELcoder** [comment]
But cDvbDevice::OpenFilter/CloseFilter() PIDs selection work on independet file handles. Therfore the main file opened in cDvbDevice::DvbOpen() is not affected.

Maybe we continue discussion at http://www.vdr-portal.de/index.php?page=Thread&postID=1281253#post1281253

**Comment by rofafor** [comment]
Please, provide a fix as a pull request.
