### ISSUE TITLE
Config Directory in resource tree?

### ISSUE THREAD

**Issue by nafets227** [rofafor/vdr-plugin-satip#4]
I dont understand why you use cPlugin::ResourceDirectory in satip.c line 124:
SatipConfig.SetConfigDirectory(cPlugin::ResourceDirectory(PLUGIN_NAME_I18N));

Why not use cPlugin::configDirectory instead?

I detected it while setting my vdr4arch, where resource directory is in /usr/share/vdr and not writeable to vdr user, whereas config directory is /var/lib/vdr that can be written by vdr user.

Stefan

**Comment by rofafor** [comment]
This is just a copy paste leftover from the iptv plugin. I'll remove it completely from satip as there's no need for it.
