### ISSUE TITLE
Reception Issues

### ISSUE THREAD

**Issue by chris281080** [rofafor/vdr-plugin-satip#41]
I am using Debian Stable (Stretch) with latest updates and a manual compiled Vanila VDR 2.3.8 with the current GIT Version of vdr-plugin-satip.
SAT>IP Server is a "Telestar DIGIBIT R1" with the current satip-axe Firmware. (I also tried an older version of satip-axe and the stock firmware of the receiver)
My configuration already worked with older software versions. (I had VDR 2.2 with an older vdr-plugin-satip verision and an older satip-axe version)

Using this configuration I currenly can't get stable TV picture or sound (a lot of artefacts).
Using the Android App "tivizen" I get a stable picture and sound, so I dont think its an major issue on my SAT>IP Server. (Using an android phone over an access point in the same network as my VDR Server.)

VDR Logging is attached:
[VDR log.txt](https://github.com/rofafor/vdr-plugin-satip/files/1229386/VDR.log.txt)

The first block of the log is the start of the VDR with minimum plugins (satip & vnsiserver) which returns already the first SATIP-ERRORs
The second block of the log is starting KODI (as client) and switching to an channel which return even more SATIP-ERRORs.

I already tried older versions of vdr-plugin-satip but had no success so far.
I also tried smarttvplugin as output plugin (instead of vnsiserver) but I had the same problem.

Can you give me any advice how I can identify the issue?

**Comment by chris281080** [comment]
Some trace information of the VDR Start:
[VDR Log Trace.zip](https://github.com/rofafor/vdr-plugin-satip/files/1229530/VDR.Log.Trace.zip)

**Comment by rofafor** [comment]
I'd need a network capture (tcpdump/wireshark) of SAT>IP server communication with the Android app. The regular RTSP port (554) should be enough.

**Comment by chris281080** [comment]
Thx, I will delivery a trace in a few days.

**Comment by chris281080** [comment]
I was just able to generate a limited trace between my Android App "tivizen" and my SAT>IP Server:
[SATIP RTSP only.pcapng.gz](https://github.com/rofafor/vdr-plugin-satip/files/1232201/SATIP.RTSP.only.pcapng.gz)

I saved the full trace localy so I can send you more details if needed.

**Comment by rofafor** [comment]
Everything looks exactly as with VDR, so your problem is most likely in the network configuration of your VDR host. You're getting a lot of networking timeouts.

**Comment by rofafor** [comment]
Everything looks exactly as with VDR, so your problem is most likely in the network configuration of your VDR host. You're getting a lot of networking timeouts, so start by double-checking your network settings (firewalls, routes, ...) and cabling/switches.

**Comment by chris281080** [comment]
Thx, I will check it. As recordings from VDR using VNSI played  fine I thought network ist not the problem, but I will test it further and close the issue till I found something useful.

**Comment by chris281080** [comment]
I did a some more analyzes with Wireshark on my VDR Server and detected. That even if there nearly no traffic, there are packet loss.
I checked the cabling and detected that another cable caused that the network cable had a not so good connection.
