### ISSUE TITLE
curl_easy_setopt(CURLOPT_MAX_RECV_SPEED_LARGE, eMaxDownloadSpeedMBits * 131072L) [rtsp.c,168] failed: A libcurl function was given a bad argument (43)

### ISSUE THREAD

**Issue by meijkl** [rofafor/vdr-plugin-satip#48]
I could resolve a lot of issues of my Debian Testing/VDR 2.3.8 system step by step this week but one message didn't go away:

  curl_easy_setopt(CURLOPT_MAX_RECV_SPEED_LARGE, eMaxDownloadSpeedMBits * 131072L)  
  [rtsp.c,168] failed: A libcurl function was given a bad argument (43)

Hopefully solved it by compiling your latest satip code plus changing rtsp.c line 168
from:   SATIP_CURL_EASY_SETOPT(handleM, CURLOPT_MAX_RECV_SPEED_LARGE, eMaxDownloadSpeedMBits * 131072L);
to:       SATIP_CURL_EASY_SETOPT(handleM, CURLOPT_MAX_RECV_SPEED_LARGE, (curl_off_t)(eMaxDownloadSpeedMBits * 1048576));

Speed may be a little bit high (20MByte versus 8-10MBytes HD streams) but so far I had no error messages. One group of messages (user.log) shows that the value may be to high:

  recordingaction: executing /usr/share/vdr/recording-hooks/R90.custom  as shell script
  [2658] channel 161 (Das Erste HD) event Tue 13.02.2018 09:20-11:00 (VPS: 13.02. 09:20) 'Sportschau - Olympia Pyeongchang 2018' status 4
   [2695] i/o throttle activated, count = 1 (tid=2695)
   [2695] buffer usage: 70% (tid=2694)
   [2695] buffer usage: 80% (tid=2694)
   [2695] buffer usage: 60% (tid=2694)
   [2695] i/o throttle released, count = 0 (tid=2695)

It appeared only one time directly after starting the recording of a HD channel. Maybe I'll decrease the value a little bit but currently I'm not experiencing package losses.
 
Klaus

**Comment by rofafor** [comment]
The whole speed limit could be removed as SAT>IP is streaming live transmissions only and buffering should be quite static.

**Comment by meijkl** [comment]
OK, I'll recompile with line 168 commented out and give it a try.

**Comment by rofafor** [comment]
As there might be multiple HD channels streaming at once, the current limit 20Mbps is too low. Instead of increasing it, I removed it completely. If any problem arise, please, reopen the issue.
