### ISSUE TITLE
Damaged streams when channels in same bouquet

### ISSUE THREAD

**Issue by pp0815** [rofafor/vdr-plugin-satip#51]
Hello! :-)

While playing or recording two channels from the same bouquet there are a lot artifacts.

**Everything works very fine when the channels are in different bouquets**, tested up to 6 HD streams. No problems at all.

Infos: 

Selfsat IP36 (FW version 2.2.19, HW version 0.2)
-> Switch (DGS-1210-24)
-> VDR (Debian Buster), vdr-plugin-satip 2.4.0-1

```
# while starting VDR IP36 identified as:
SATIP: Adding server '192.168.178.39|DVBS2-8|SAT2IP->AS_B3S100_V2' Bind: default Filters: none CI: no Quirks: none

# Selfsat (from syslog):
Jan  1 00:00:06 kernel: DVB: registering new adapter (Abilis TB100 DVB framework)
Jan  1 00:00:11 kernel: MxLWare 2.1.1.7-RC100, F/W 2.1.1.7-RC100, chip MXL584, Id 1, Ver 2
Jan  1 00:00:11 kernel: tb100_adapter tb100-dvb-adapter0.8: DVB: registering adapter 7 frontend 0 (Hydra)...
Jan  1 00:00:12 kernel: tb100_adapter tb100-dvb-adapter0.8: LPU0, tb100_sp_fw V1.0 (Sep 12 2014 08:51:48)
Jan  1 00:00:12 kernel: DVB: registering new adapter (Abilis TB100 DVB framework)
...

# cat /proc/sys/net/core/rmem_default && cat /proc/sys/net/core/rmem_max
212992
212992

# vdr -V
vdr (2.4.0/2.4.0) - The Video Disk Recorder
satip (2.4.0) - SAT>IP Devices
vnsiserver (1.6.0) - VDR-Network-Streaming-Interface (VNSI) Server

# grep satip /var/lib/vdr/setup.conf 
satip.CICAM = 0 0
satip.DisabledFilters = 
satip.DisabledSources = 
satip.EnableCIExtension = 0
satip.EnableEITScan = 0
satip.OperatingMode = 3
satip.TransportMode = 0

# cat /etc/vdr/conf.d/50-satip.conf 
[satip]
-d 7
# tried quirks in different combinations, but no effekt at all:
-s 192.168.178.39|DVBS2-8|SAT2IP->AS_B3S100_V2|0x7f

# from channels.conf twochannels in same bouquet showing this effect:
KiKA HD;ZDFvision:11347:VC23M5O35P0S1:S19.2E:22000:6610=27:6620=deu@3,6621=mis@3;6622=deu@106:6630;6631=deu:0:11160:1:1010:0
3sat HD;ZDFvision:11347:VC23M5O35P0S1:S19.2E:22000:6510=27:6520=deu@3,6521=mis@3,6523=mul@3;6522=deu@106:6530;6531=deu:0:11150:1:1010:0

```

There is nothing in the logs which is relevant. What else can i do?

What do you think: problem exists in plugin or vdr?

Thanks a lot for your time and efforts.

**Comment by unf** [comment]
I would rather bet on an issue with your SAT>IP Server. Receiving different channels from the same transponder is one functionality that has been tested and proofed in many setupos with vdr & vdr-plugin-satip from the very beginning of the plugin. There's also a slight chance for a network issue, but since you say you can receive several channel in parallel from different transponders ...

**Comment by rofafor** [comment]
Please, test with another program, whether you really can stream the whole mux without errors from your SAT>IP server. Using VLC with "pids=all" parameter should do the trick. The current channel URL is available via SVDRP command or setup menu and just replace possible "addpids/delpids" parameters with the mentioned "pids=all".

**Comment by pp0815** [comment]
Thank for your very quick response, wow! :-)

Further tests shows, that the problem exists only for HD channels in **one** transponder in the vertical lowband. All other HD channels are horizontal and work without any problems, even all SD channels.

Sorry for that, - obviously the error is something completely different.

Thank you, have a nice day!
