### ISSUE TITLE
Wrong URI for x_pmt if it's the only parameter

### ISSUE THREAD

**Issue by mjanser** [rofafor/vdr-plugin-satip#52]
When using the plugin with a Octopus NET it sometimes tries to do requests like `rtsp://[ip]/stream=1&x_pmt=2000` for encrypted channels. This request looks wrong because there should be a `?` instead of `&`. The Octopus NET answers with a status code 400.

Is there a check missing here?
https://github.com/rofafor/vdr-plugin-satip/blob/299296bbb1a7274e7c67abee64a6edc24bf965bc/tuner.c#L512

The check is done some lines above:
https://github.com/rofafor/vdr-plugin-satip/blob/299296bbb1a7274e7c67abee64a6edc24bf965bc/tuner.c#L499

**Comment by rofafor** [comment]
Yes, you're correct - I've never witnessed this situation as there have always been some pids defined.
