### ISSUE TITLE
Artifacts in vdr only when channels in same transponder 

### ISSUE THREAD

**Issue by pp0815** [rofafor/vdr-plugin-satip#55]
Reopens https://github.com/rofafor/vdr-plugin-satip/issues/51 (It was not only on low band, sorry.)

As mentioned in the old thread i tested with vlc and "pids=all". VLC is running without any problems, no artifacts at all.

```
1 | RTSP Dynamic | 192.168.178.23 | yes/yes | -38.75 | 100.00 | 11494H22000 | DVBS2/8PSK | 0,17,18,5100,5101,5102,5104

2 | RTSP Dynamic | 192.168.178.23 | yes/yes | -38.75 | 100.00 | 11493H22000 | DVBS2/8PSK | 5101,5102,5103,5104,5105,5106,18,20,0,16,17
```
Above status of webinterface of Selfsat IP36: 1 = VDR,  2= VLC

VLC started with
```
$ cat test.m3u
#EXTINF:0,1. Das Erste HD
rtsp://192.168.178.39/?src=1&freq=11494&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&plts=on&sr=22000&fec=23&pids=all
```
See https://files.pepre.de/vlc-satip.png for VLC mediainfo.

I don't know wether this is an issue of satip-plugin or vdr. But with the old HW (SAT TV pci-cards) this problem did not exist.

Any help would be greatly appreciated.

Thanks a lot for your time and efforts.

**Comment by pp0815** [comment]
I don't think so. Wireshark shows no errors at all, and the switch (D-Link DGS-1210-24) is not the problem.

**Comment by Karl-opec** [comment]
This might also be related. The megasat 8000 satip3 server seams to be based on the same design. 

https://github.com/tvheadend/tvheadend/pull/882#issuecomment-238661222

**Comment by rofafor** [comment]
@pp0815, you could add a simple `return Receiving();` line before the `if Receiving())` block found at https://github.com/rofafor/vdr-plugin-satip/blob/master/device.c#L285. That should do trick, but it has been a long time when I touched that part of the code and therefore might have overlooked something...

**Comment by pp0815** [comment]
@rofafor, thank you for your quick response.
```
# diff -u1 device.c device.c.patched 
--- device.c    2018-11-15 07:35:08.075341875 +0100
+++ device.c.patched    2018-11-15 07:34:45.343235069 +0100
@@ -284,2 +284,3 @@
      if (priorityP > IDLEPRIORITY) {
+        return Receiving(); 
         if (Receiving()) {
```
Sorry, no 2nd stream, even from another transponder. And sometimes (?!) no stream at all.

**Comment by pp0815** [comment]
```
# diff -c1 device.c.orig device.c
*** device.c.orig       2019-02-26 13:21:44.200104336 +0100
--- device.c    2019-02-26 12:50:52.402295958 +0100
***************
*** 285,286 ****
--- 285,287 ----
          if (Receiving()) {
+            return false;
             if (IsTunedToTransponder(channelP)) {
```
This is working as expected. :-)

**Comment by pp0815** [comment]
Better:

```
bool cSatipDevice::ProvidesChannel(const cChannel *channelP, int priorityP, bool *needsDetachReceiversP) const
{
  bool result = false;
  bool hasPriority = (priorityP == IDLEPRIORITY) || (priorityP > this->Priority());
  bool needsDetachReceivers = false;

  debug9("%s (%d, %d, %d) [device %u]", __PRETTY_FUNCTION__, channelP ? channelP->Number() : -1, priorityP, !!needsDetachReceiversP, deviceIndexM);

  if (channelP && ProvidesTransponder(channelP)) {
     result = hasPriority;
     if (priorityP > IDLEPRIORITY) {
        if (Receiving()) {
           needsDetachReceivers = true;
           result = true;
           }
        }
     }
  if (needsDetachReceiversP)
     *needsDetachReceiversP = needsDetachReceivers;
  return result;
}
```
