### ISSUE TITLE
detectsatip.py issue

### ISSUE THREAD

**Issue by 9000h** [rofafor/vdr-plugin-satip#56]
Hi,
detectsatip.py will not find Panasonic TV's, the plugin did found it.

[ddd.zip](https://github.com/rofafor/vdr-plugin-satip/files/2669764/ddd.zip)
OS Ubuntu 18.04
this is the output, the Panasonic is not shown
```
./detectsatip.py
[
  {
    "frontends": {
      "DVBC": 2, 
      "DVBC2": 2, 
      "DVBS2": 4, 
      "DVBT2": 2
    }, 
    "name": "minisatip"
  }, 
  {
    "frontends": {
      "DVBC": 4
    }, 
    "name": "FRITZ!Box 6490 Cable"
  }
]
```
CU
9000h

**Comment by rofafor** [comment]
You could try to increase the socket timeout, if the Panasonic is just answering too slowly: `sock.settimeout(1)`

**Comment by 9000h** [comment]
the timeout setting did not help
here are the capture
[detect.zip](https://github.com/rofafor/vdr-plugin-satip/files/2729733/detect.zip)

**Comment by rofafor** [comment]
A workaround is implemented in https://github.com/rofafor/vdr-plugin-satip/commit/66d7aae89dba965eac73520e7dc5ce5896d8a3ae

**Comment by 9000h** [comment]
looks good now
```
[
  {
    "frontends": {
      "DVBC": 2, 
      "DVBC2": 2, 
      "DVBS2": 4, 
      "DVBT2": 2
    }, 
    "name": "minisatip"
  }, 
  {
    "frontends": {
      "DVBC": 4
    }, 
    "name": "FRITZ!Box 6490 Cable"
  }, 
  {
    "frontends": {
      "DVBC": 1
    }, 
    "name": "43CX750_Series"
  }
]
```
