### ISSUE TITLE
code bug in frontend selection

### ISSUE THREAD

**Issue by hubsif** [rofafor/vdr-plugin-satip#57]
Hi!

First of all thanks for that plugin, which enables me to return from a short tvheadend trip! ;)

But as it seems, I might be the only one requiring the "frontend selection feature", cause I think I found a bug in the source code preventing this from working at all:
In [param.c#L167](https://github.com/rofafor/vdr-plugin-satip/blob/66d7aae89dba965eac73520e7dc5ce5896d8a3ae/param.c#L167) if using a RID > 100, the query string gets started with `"&fe=%d"` and then in the next line followed by `"src=%d&"`, which results in a URL path like `/?&fe=2src=2&freq=...`, which is obviously not correct.

I fixed it by move the ampersand to the end, like this `"fe=%d&"`. I'm not sure if that's a correct fix though, as I didn't verify what else happens to the query string before and after.

Background:
I'm using a _Digibit Twin_ device with two LNBs aligned to different satellites. In order to be able to use channels from both satellite positions, I need to pin them to the corresponding _frontend_ (=tuner), since I haven't found a way to tell the device about different _sources_ (=satellite positions).

BR,
hubsif.

**Comment by rofafor** [comment]
Should be fixed in https://github.com/rofafor/vdr-plugin-satip/commit/b697e435d4bf42754309e6b5a9c5f8ff43463077

**Comment by rofafor** [comment]
No responses, so I guess this is fixed now.
