### ISSUE TITLE
ClearQAM/ATSC support?

### ISSUE THREAD

**Issue by ctr49** [rofafor/vdr-plugin-satip#59]
Is there support for ClearQAM/ATSC yet? If so, which delivery system shall be used?

I have a remote vdr with an attached ClearQAM tuner (Sundtek), that is also SAT>IP capable.
Using vdr with the locally attached tuner, "A" (for ATSC) is used as delivery system and this also works (more or less) with streamdev-server/streamdev-client to a remote vdr. However, since I really just need the remote tuner I would rather like to use it as SAT>IP remote tuner and use the satip on my main vdr.

**Comment by rofafor** [comment]
SAT>IP specs (1.2.2.) don't support ATSC, so no support has been made. However, minisatip seems to have an unofficial support, so the implementation should be quite simple.

**Comment by 9000h** [comment]
there is one device from Hauppauge "Cordcutter TV" which has also ATSC/ClearQAM SAT>IP support appart from minisatip and tvheadend.
refercence: https://forums.plex.tv/t/help-with-dvb-ip-server-discovery-hauppauge-cordcutter-tv/220149
https://tvheadend.org/issues/5728

**Comment by rofafor** [comment]
I've committed a preliminary support (I don't have a setup to test this): https://github.com/rofafor/vdr-plugin-satip/commit/a3fa5865f33a0cc38b36f6d7b87229975451850d
