### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by M-Reimer** [rofafor/vdr-plugin-satip#69]
The last release was tagged over 2 years ago and a few fixes were pushed to GIT in the mean time. Is there any plan when the next release will happen?

**Comment by rofafor** [comment]
I'll try to make one more fix before a new release.

**Comment by wirbel-at-vdr-portal** [comment]
Three and a half month later now. What about now, about two month no change?

**Comment by rofafor** [comment]
Still open bugs and no pull requests for fixes.

**Comment by rofafor** [comment]
2.4.1 tagged
