### ISSUE TITLE
question about your website

### ISSUE THREAD

**Issue by madmartin** [rofafor/vdr-plugin-satip#70]
Hello Rolf,

Today I discovered that your home- and download site http://www.saunalahti.fi/*** is not reachable.
The email *** is also undeliverable, 

Is this a failure or did you give it up? If yes, is there a new website and/or email or will I find everything on github from now on?
Please let us know.

Greetings from Berlin, Germany
Martin

CC @hd_brummy

**Comment by rofafor** [comment]
I just haven't been used VDR for a few years anymore - everything should be already on github except patches. I'll try to motivate myself for finalizing the repos and open issues.

Just tested the email and worked for me.
