### ISSUE TITLE
Glitches when switching channels

### ISSUE THREAD

**Issue by pipelka** [rofafor/vdr-plugin-satip#72]
If multiple clients are connected there are glitches on switching channels.

Scenario:

- Client 1 watches channel A
- Client 2 watches channel B
- Client 1 switches to channel C
- Client 2 experiences a glitch (video distortion)

I narrowed it down to commit df819058211431d249cdc2a0af3ddfefd6c231bf.
Removing this commit removes the problem.

**Comment by hpannenb** [comment]
@pipelka Which SAT>IP device are You using?

**Comment by pipelka** [comment]
Kathrein EXIP 418.

**Comment by rofafor** [comment]
Does disabling frontend reuse in the setup menu have any effect on the issue?

**Comment by rofafor** [comment]
Please, test the latest master,

**Comment by pipelka** [comment]
My magic orb says that it will work. It's essentially the same as reverting the commit in my case. ;-)
But I will test it, ...

**Comment by pipelka** [comment]
Ok. It's working now without glitches.
I tested it with frontend reuse enabled and disabled.
Thanks.
