### ISSUE TITLE
create satip.h

### ISSUE THREAD

**Issue by tenzap** [rofafor/vdr-plugin-satip#73]
Hello,

 [w_scan_cpp](https://www.gen2vdr.de/wirbel/w_scan_cpp/index2.html) uses satip in his project. Right now in its Makefile it creates a `satip.h` header file based on what is in `satip.c`
Would it be possible to split this ? 

This would 
- ease the reuse of your plugin by other projects
- permit to reference it as a dependency in package management systems like on debian

**Comment by tenzap** [comment]
if this doesn't make sense (since I don't know VDR and its plugin system), please ignore this :)

**Comment by rofafor** [comment]
I find it quite odd a channel scanner to use satip plugin instead interfacing directly via SAT/IP protocol. Anyway, what should be included in that header? Just the `cPluginSatip` class definition?

**Comment by tenzap** [comment]
Seems so + renaming of VERSION & DESCRIPTION, these are the changes he applies
```
	sed -i 's/VERSION/SATIP_VERSION/' ./vdr/PLUGINS/src/satip/satip.h
	sed -i 's/DESCRIPTION/SATIP_DESCRIPTION/' ./vdr/PLUGINS/src/satip/satip.h
	sed -i '1i\\nclass cSatipDiscoverServers;\n' ./vdr/PLUGINS/src/satip/satip.h
	sed -i '1i\extern const char SATIP_DESCRIPTION[];' ./vdr/PLUGINS/src/satip/satip.h
	sed -i '1i\extern const char SATIP_VERSION[];' ./vdr/PLUGINS/src/satip/satip.h
	sed -i '1i\#include <vdr\/plugin.h>\n' ./vdr/PLUGINS/src/satip/satip.h
	sed -i '1i\#pragma once' ./vdr/PLUGINS/src/satip/satip.h
	sed -i 's/VDRPLUGINCREATOR/\/\/VDRPLUGINCREATOR/g' ./vdr/PLUGINS/src/satip/satip.c
	sed -i 's/class cPluginSatip/\#include \"satip.h\"\n \/* class cPluginSatip/' ./vdr/PLUGINS/src/satip/satip.c
	sed -i 's/cPluginSatip\:\:cPluginSatip(void)/*\/\ncPluginSatip\:\:cPluginSatip(void)/' ./vdr/PLUGINS/src/satip/satip.c
	sed -i 's/const char VERSION\[\]/const char SATIP_VERSION\[\]/' ./vdr/PLUGINS/src/satip/satip.c
	sed -i 's/static const char DESCRIPTION\[\]/const char SATIP_DESCRIPTION\[\]/' ./vdr/PLUGINS/src/satip/satip.c
	sed -i 's/const char VERSION\[\]/const char SATIP_VERSION\[\]/' ./vdr/PLUGINS/src/satip/common.h
	sed -i 's/VERSION/SATIP_VERSION/g' ./vdr/PLUGINS/src/satip/discover.c
	sed -i 's/VERSION/SATIP_VERSION/g' ./vdr/PLUGINS/src/satip/rtsp.c
```

**Comment by rofafor** [comment]
Sorry, not going to do this as the result would differ too much from my liking.
