### ISSUE TITLE
Session times out on EXIP418 when timeout is equal to eMinKeepAliveIntervalMs

### ISSUE THREAD

**Issue by Rayn0r** [rofafor/vdr-plugin-satip#78]
On my current installation of vdr-2.4.6 together with the satip plugin, it occured quite frequently, that a session timed out on HD channels. SD channels were mostly unaffected, although I had TS discontinuities now and then.
My Kathrein EXIP418 advertises a timeout of 30 seconds. The standard timeout (eMinKeepAliveIntervalMs) in satip is also 30 seconds.
Lowering the timeout by 10% and allowing a timeout less than eMinKeepAliveIntervalMs, resulted in steady uninterrupted streams.

This is the diff:
```
diff --git a/rtsp.c b/rtsp.c
index 63e6dfa..3b20461 100644
--- a/rtsp.c
+++ b/rtsp.c
@@ -433,7 +433,7 @@ void cSatipRtsp::ParseHeader(void)
            int timeout = -1;
            char *session = NULL;
            if (sscanf(r, "Session:%m[^;];timeout=%11d", &session, &timeout) == 2)
-              tunerM.SetSessionTimeout(skipspace(session), timeout * 1000);
+              tunerM.SetSessionTimeout(skipspace(session), timeout * 900); // 900 instead of 1000: lets keep the timeout 10% lower than advertised
            else if (sscanf(r, "Session:%m[^;]", &session) == 1)
               tunerM.SetSessionTimeout(skipspace(session), -1);
            FREE_POINTER(session);
diff --git a/tuner.c b/tuner.c
index cd8366b..21bc60c 100644
--- a/tuner.c
+++ b/tuner.c
@@ -392,7 +392,7 @@ void cSatipTuner::SetSessionTimeout(const char *sessionP, int timeoutP)
   sessionM = sessionP;
   if (nextServerM.IsQuirk(cSatipServer::eSatipQuirkSessionId) && !isempty(*sessionM) && startswith(*sessionM, "0"))
      rtspM.SetSession(SkipZeroes(*sessionM));
-  timeoutM = (timeoutP > eMinKeepAliveIntervalMs) ? timeoutP : eMinKeepAliveIntervalMs;
+  timeoutM = (timeoutP < eMinKeepAliveIntervalMs) ? timeoutP : eMinKeepAliveIntervalMs;
 }

 void cSatipTuner::SetupTransport(int rtpPortP, int rtcpPortP, const char *streamAddrP, const char *sourceAddrP)
```
I'd very much like to hear your thoughts on this.

**Comment by rofafor** [comment]
Satip specification states:
> the timeout value shall not be less than 30 seconds. The recommended value is 60 seconds.

I'd check how much jitter is in these OPTIONS (keepalive) commands in your system. The Katrein device itself should have some tolerance as well due to separate system clocks.

**Comment by Rayn0r** [comment]
The Kathrein box really seems to be one stubborn piece of electronics :-(.
...and it was so much easier if everyone would stick to the guidelines of the spec...

I wrote a few test lines in Python (with some borrowed code from https://pypi.org/project/rtsp-curl/)
Parts of the code look like this:
```
timeout = 30
rtsp.rtsp_play(f"{stream_uriip}{streamid}?addpids=0,16,17,18,20")
print("after PLAY")

for i in range(1, 5):
    print(f"sleeping {timeout} seconds")
    time.sleep(timeout)
    print(f"maintain: {i}")
    rtsp.rtsp_options(stream_uriip)
```
When setting the timeout to 30, the response headers look like this with a 454 error:
```
< RTSP/1.0 200 OK
< RTP-Info:url=rtsp://10.6.66.254/stream=269;seq=59556
< CSeq:4
< Session:2ea43327ba26718
<
* Connection #0 to host 10.6.66.254 left intact
after PLAY
sleeping 30 seconds
maintain: 1
* Found bundle for host 10.6.66.254: 0x110cae0 [can pipeline]
* Re-using existing connection! (#0) with host 10.6.66.254
* Connected to 10.6.66.254 (10.6.66.254) port 554 (#0)
> OPTIONS rtsp://10.6.66.254/ RTSP/1.0
CSeq: 5
Session: 2ea43327ba26718
User-Agent: MadYel RTSP

< RTSP/1.0 454 Session Not Found
< CSeq:5
< Session:2ea43327ba26718
< Content-Length: 0
```
Setting it to 29.9 results in a maintained session:
```
< RTSP/1.0 200 OK
< RTP-Info:url=rtsp://10.6.66.254/stream=268;seq=35840
< CSeq:4
< Session:2e91477354eb03b
<
* Connection #0 to host 10.6.66.254 left intact
after PLAY
sleeping 29.9 seconds
maintain: 1
* Found bundle for host 10.6.66.254: 0x2af1ae0 [can pipeline]
* Re-using existing connection! (#0) with host 10.6.66.254
* Connected to 10.6.66.254 (10.6.66.254) port 554 (#0)
> OPTIONS rtsp://10.6.66.254/ RTSP/1.0
CSeq: 5
Session: 2e91477354eb03b
User-Agent: MadYel RTSP

< RTSP/1.0 200 OK
< Public:OPTIONS,SETUP,PLAY,TEARDOWN,DESCRIBE
< CSeq:5
< Session:2e91477354eb03b
```
Jitter on the local net is probably neglectable. 10 pings to the Kathrein box from VDR itself look like this:
```
--- 10.6.66.254 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9205ms
rtt min/avg/max/mdev = 0.119/0.208/0.247/0.037 ms
```
So it seems, that I may have to keep this as a private fix.

**Comment by Rayn0r** [comment]
To be honest... The timeout is not shorter than 30 seconds. They stuck to the spec precisely.
We just need to answer a wee bit before the 30 seconds are over in order to maintain the session.

**Comment by 9000h** [comment]
the spec says
"Clients  need  to  send  an  OPTIONS  message at  the  latest  a  few  seconds  before each expiration  period.  As OPTIONS messages are delivered using reliable TCP transport, there is no need to send excess OPTIONS messages.The  OPTIONS  method  may  also be  invoked  out-of-session by  clients  to  query  servers  on  supported  RTSP  methods"

so the OPTIONS keepalive can not be the same value as the timeout

**Comment by rofafor** [comment]
@9000h Thanks. How an earth I've missed that chapter. Anyway, I'll fix the plugin code accordingly.

**Comment by 9000h** [comment]
hmm, there is maybe some more in regards to keepalive and the use of OPTIONS
https://github.com/catalinii/minisatip/commit/484d8a78d09f62e47f9f624bcbf226bdaef29031

**Comment by rofafor** [comment]
The latest master contains now a commit https://github.com/rofafor/vdr-plugin-satip/commit/417d4ed8fcea95cb966a8ef3e1b9b7906b9255be. Please, test.

**Comment by Rayn0r** [comment]
First tests look good. OPTIONS are sent out every 28 seconds with an advertised timeout of 30 seconds.

**Comment by Rayn0r** [comment]
> The latest master contains now a commit [417d4ed](https://github.com/rofafor/vdr-plugin-satip/commit/417d4ed8fcea95cb966a8ef3e1b9b7906b9255be). Please, test.

It's been running stutter-free ever since above commit.
I'd say it's safe to close the issue.
