### ISSUE TITLE
plugin reports signal strength in dBm wrong to vdr, if server reports zero signal strength

### ISSUE THREAD

**Issue by wirbel-at-vdr-portal** [rofafor/vdr-plugin-satip#80]
The satip plugin doesnt report signal strength as given by spec.
The spec v1.2.2 says on page 39:

Signal level - Numerical value between 0 and 255
An incoming L-band satellite signal of
-25dBm corresponds to 224
-65dBm corresponds to 32
No signal corresponds to 0

'no signal' aka '0mV' cannot be expressed in dBm due to logarithm:
10*log10(0mV/1mV) -> undefined
Instead of refusing to report any signal strength for zero value from server,
the plugin reports in cSatipDevice::SignalStats() a wrong value for
Strength : -71.67dBm:

40.0 * ('0' - 32) / 192.0 - 65.0 == -71,667
One valid solution could be in cSatipDevice::SignalStats():

--   Valid |= DTV_STAT_VALID_STRENGTH;
++   if (*Strength > -71.5) /* (-71,667 > threshhold > -71.458) */
++      Valid |= DTV_STAT_VALID_STRENGTH;

see also:

----

device.c:219
bool cSatipDevice::SignalStats(int &Valid, double *Strength, double *Cnr, double *BerPre, double *BerPost, double *Per, int *Status) const
{
  debug16("%s [device %u]", __PRETTY_FUNCTION__, deviceIndexM);
  Valid = DTV_STAT_VALID_NONE;
  if (Strength && pTunerM) {
     *Strength =  pTunerM->SignalStrengthDBm(); //<<<<<<<< dBm comes here
     Valid |= DTV_STAT_VALID_STRENGTH;          //<<<<<<<< valid for 1..255 or -71.458..-18.541 only.
     }

----

tuner.c:350 in void cSatipTuner::ProcessApplicationData(u_char *bufferP, int lengthP)

        signalStrengthDBmM = (value >= 0) ? 40.0 * (value - 32) / 192.0 - 65.0 : 0.0; //<<<<<<<<<<< from here

**Comment by wirbel-at-vdr-portal** [comment]
typo, sorry.

if (Strength > -71.5) /* (-71,667 < threshhold < -71.458) */

**Comment by wirbel-at-vdr-portal** [comment]
Related to that, the initialization of signalStrengthDBmM to 0.0 in tuner.c:46 and tuner.c:280 is also wrong.

0.0 dBm is equal to a power of 1mWatt, or +108.75dBµV of signal strength, which is a way too large signal for any type of dvb.

**Comment by wirbel-at-vdr-portal** [comment]
Hi Rolf,

as you're not willing to/going to respond at all - now seen several times in the past - you may (or may not, as you like) close this bug. I'm not interested to contribute anymore.

**Comment by madmartin** [comment]
Hello @wirbel-at-vdr-portal ,

maybe you add a patch here as a pull request?
If it is then not be merged officially, every package maintainer can decide on his own to add this patch / PR content  to his binary package or not.
So - at least - I am interested.

Martin

**Comment by haarm** [comment]
I would also be interested in

**Comment by wirbel-at-vdr-portal** [comment]
After 1.5 years, my interest is somewhat limited to do so.

**Comment by haarm** [comment]
I can understand well

**Comment by CvH** [comment]
@madmartin everyone can PR these changes no need to wait for someone, just declare at the PR where the fix is originated and done
