### ISSUE TITLE
caid replace possibility

### ISSUE THREAD

**Issue by Pitty01** [rofafor/vdr-plugin-satip#9]
Hello

is it possible to implement a setting for a default caid replacement to 1a or somethings else which enables the possibility to choose the channel on vdr connected to satip server with serverside decryption.

Otherwise u always have to hack channels.conf (as u remember from prior streamdev times) to switch vdr.

thanks
Pitty

**Comment by rofafor** [comment]
What's the problem with current plugin configuration: you'll just define the encryption you're using into the correct slot?

**Comment by Pitty01** [comment]
no, there is only decryption on the server, not on the cleint, the stream comes "as FTA" when u connect to it and there is no further decryption needed (setting satip.EnableCIExtension = 0). It's only the vdr who rejects in that case switching to that channel because of the caid in channels.conf string (channel not available message).

**Comment by rofafor** [comment]
Now I understand your problem. However, adding such feature into the plugin would be idiotic as the server should also remove caids if it really does the decryption.

Anyway, which server are you using? Setting the EnableCIExtension to one might actually help you if the server doesn't mind about the X_PMT/CI extension as it tells VDR that the device has an integrated CAM and can handle the decryption.

**Comment by Pitty01** [comment]
minisatip with current git version

I'll try with EnableCIExtension = 1

**Comment by Pitty01** [comment]
seems working - so far u can say it works for the moment. but for the moment is seems that the bahavior is same as replace caid by 1a. Its a cutting edge version working not very well in this forst release.

thanky
